### ISSUE TITLE
how to implement a task queue

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#101]
https://github.com/GoogleCloudPlatform/appengine-taskqueue-counter/

http://stackoverflow.com/questions/4085075/how-to-get-the-return-value-like-ajax-using-task-queue-on-google-app-engine

**Comment by bdaudert** [comment]
Took a shot at it. 
main.py
TimeSeriesWorker

processingMethods.py
code commented out

Issue:   
File "/Users/bdaudert/Google-Drought/WebInterface/main.py", line 262, in post
    data = collection.filterDate(start, end).getRegion(points,1).slice(1).getInfo()
AttributeError: 'unicode' object has no attribute 'filterDate'

So somehow the collection is passed to the worker as a unicode object rather than a ee collection.
??
