### ISSUE TITLE
domainType set to full when shouldn't be

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#119]
after the splitting of the forms... we have a new error to deal with (this was fine in the version before the form split). 

after submitting the form: 

https://github.com/Google-Drought/WebInterface/blob/development/templates/includes/scripts.php#L224

so it should be 'singlemappoint'

It does get set to 'singlemappoint' temporarily... 
but with the post... it gets set back to 'full' in the template... 

same thing happens with the download: 

https://github.com/Google-Drought/WebInterface/blob/development/templates/includes/mapdownloadoptions.html#L56

domainType = 'rectangle'
but it gets set back to 'full' on post.

**Comment by bdaudert** [comment]
previously domainType was set in timeseriesrequired. After form split I needed to set that variable in both forms separately so that on submit of either form, the domainType is passed to main.py as input. 

This is fixed now.

I commented out the old way of defining domainType in timeseriesrequired and just set a hidden variable with name, class domainType. The id of that element is domainType for form_map, domainTypeTS for form_ts

As far as I can see, this should not cause any further issues
