### ISSUE TITLE
Landsat points between missing value points not shown in high charts

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#66]
Highcharts is not connecting over the missing values in Landsat data or showing the points in spline type. 

This causes a real problem, esp for points that are surrounded by missing values.. 
which do not show up on the map at all in spline type. THey show up in scatter plot, though.

**Comment by bdaudert** [comment]
I think I fixed that as best I could. I believe that the issue was that None values came as strings and therefore were not converted to javascript null values. Highcharts need null values in its graphs. 

Code changed in figureFormatting.set_initial_time_series and figureFormatting.join_time_series_data:
if isinstance(val,basestring):
            data_dict_graph['Data'].append([time,None])
        else:
            data_dict_graph['Data'].append([time,val])
